### ISSUE TITLE
Crear tarea no maneja correctamente la validación

### ISSUE THREAD

**Issue by D3AH** [expokinal2019/Backend#7]
En el caso de que falte un parametro para crear la tarea la función se salta el primer `if` y no responde a la petición.

https://github.com/expokinal2019/Backend/blob/f43fb6b15619ff6cd8c24ed3b5f812f3f820b9ad/src/controllers/taskController.js#L12

**Comment by Chofito** [comment]
Estoy esperando unos cambios de @cristiaan05

**Comment by Chofito** [comment]
@D3AH lo estas ejecutando local o usas heroku? si usas heroku entonces el problema esta en index.js

**Comment by D3AH** [comment]
Local.

**Comment by Chofito** [comment]
@cristiaan05 subio unos cambios, probalos y me contas, solo asegurate de cambiar la url de mongo en index.js

**Comment by cristiaan05** [comment]
sigue el error?
